# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lh_gui.ui'
#
# Created: Wed Feb 15 06:11:34 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_lh_gui(object):
	def setupUi(self, lh_gui):
		lh_gui.setObjectName(_fromUtf8("lh_gui"))
		lh_gui.resize(450, 301)
		self.buttonBox = QtGui.QDialogButtonBox(lh_gui)
		self.buttonBox.setGeometry(QtCore.QRect(330, 251, 111, 41))
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
		self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
		self.run_lh = QtGui.QPushButton(lh_gui)
		self.run_lh.setGeometry(QtCore.QRect(10, 260, 181, 31))
		self.run_lh.setObjectName(_fromUtf8("run_lh"))
		self.groupBox = QtGui.QGroupBox(lh_gui)
		self.groupBox.setGeometry(QtCore.QRect(10, 10, 191, 131))
		self.groupBox.setObjectName(_fromUtf8("groupBox"))
		self.showBase = QtGui.QCheckBox(self.groupBox)
		self.showBase.setGeometry(QtCore.QRect(0, 20, 141, 21))
		self.showBase.setObjectName(_fromUtf8("showBase"))
		self.layoutWidget = QtGui.QWidget(self.groupBox)
		self.layoutWidget.setGeometry(QtCore.QRect(0, 70, 114, 26))
		self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
		self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
		self.horizontalLayout_2.setMargin(0)
		self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
		self.label_2 = QtGui.QLabel(self.layoutWidget)
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.horizontalLayout_2.addWidget(self.label_2)
		self.baseBinSize = QtGui.QSpinBox(self.layoutWidget)
		self.baseBinSize.setMinimum(25)
		self.baseBinSize.setMaximum(200)
		self.baseBinSize.setSingleStep(5)
		self.baseBinSize.setProperty("value", 100)
		self.baseBinSize.setObjectName(_fromUtf8("baseBinSize"))
		self.horizontalLayout_2.addWidget(self.baseBinSize)
		self.layoutWidget_2 = QtGui.QWidget(self.groupBox)
		self.layoutWidget_2.setGeometry(QtCore.QRect(0, 100, 114, 26))
		self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
		self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_2)
		self.horizontalLayout_3.setMargin(0)
		self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
		self.label_3 = QtGui.QLabel(self.layoutWidget_2)
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.horizontalLayout_3.addWidget(self.label_3)
		self.baseBins = QtGui.QSpinBox(self.layoutWidget_2)
		self.baseBins.setMinimum(100)
		self.baseBins.setMaximum(400)
		self.baseBins.setSingleStep(10)
		self.baseBins.setProperty("value", 200)
		self.baseBins.setObjectName(_fromUtf8("baseBins"))
		self.horizontalLayout_3.addWidget(self.baseBins)
		self.layoutWidget1 = QtGui.QWidget(self.groupBox)
		self.layoutWidget1.setGeometry(QtCore.QRect(0, 40, 184, 26))
		self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
		self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
		self.horizontalLayout.setMargin(0)
		self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
		self.label = QtGui.QLabel(self.layoutWidget1)
		self.label.setObjectName(_fromUtf8("label"))
		self.horizontalLayout.addWidget(self.label)
		self.baseThreadInterval = QtGui.QSpinBox(self.layoutWidget1)
		self.baseThreadInterval.setMinimum(5000)
		self.baseThreadInterval.setMaximum(50000)
		self.baseThreadInterval.setSingleStep(5000)
		self.baseThreadInterval.setObjectName(_fromUtf8("baseThreadInterval"))
		self.horizontalLayout.addWidget(self.baseThreadInterval)
		self.groupBox_2 = QtGui.QGroupBox(lh_gui)
		self.groupBox_2.setGeometry(QtCore.QRect(220, 10, 211, 131))
		self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
		self.layoutWidget_3 = QtGui.QWidget(self.groupBox_2)
		self.layoutWidget_3.setGeometry(QtCore.QRect(0, 70, 114, 26))
		self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
		self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_3)
		self.horizontalLayout_4.setMargin(0)
		self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
		self.label_4 = QtGui.QLabel(self.layoutWidget_3)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.horizontalLayout_4.addWidget(self.label_4)
		self.servoBinSize = QtGui.QSpinBox(self.layoutWidget_3)
		self.servoBinSize.setMinimum(25)
		self.servoBinSize.setMaximum(200)
		self.servoBinSize.setSingleStep(5)
		self.servoBinSize.setProperty("value", 100)
		self.servoBinSize.setObjectName(_fromUtf8("servoBinSize"))
		self.horizontalLayout_4.addWidget(self.servoBinSize)
		self.layoutWidget_4 = QtGui.QWidget(self.groupBox_2)
		self.layoutWidget_4.setGeometry(QtCore.QRect(0, 100, 114, 26))
		self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
		self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget_4)
		self.horizontalLayout_5.setMargin(0)
		self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
		self.label_5 = QtGui.QLabel(self.layoutWidget_4)
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.horizontalLayout_5.addWidget(self.label_5)
		self.servoBins = QtGui.QSpinBox(self.layoutWidget_4)
		self.servoBins.setMinimum(100)
		self.servoBins.setMaximum(400)
		self.servoBins.setSingleStep(10)
		self.servoBins.setProperty("value", 200)
		self.servoBins.setObjectName(_fromUtf8("servoBins"))
		self.horizontalLayout_5.addWidget(self.servoBins)
		self.layoutWidget_5 = QtGui.QWidget(self.groupBox_2)
		self.layoutWidget_5.setGeometry(QtCore.QRect(0, 40, 199, 26))
		self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
		self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_5)
		self.horizontalLayout_6.setMargin(0)
		self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
		self.label_6 = QtGui.QLabel(self.layoutWidget_5)
		self.label_6.setObjectName(_fromUtf8("label_6"))
		self.horizontalLayout_6.addWidget(self.label_6)
		self.servoThreadInterval = QtGui.QSpinBox(self.layoutWidget_5)
		self.servoThreadInterval.setMinimum(25000)
		self.servoThreadInterval.setMaximum(2000000)
		self.servoThreadInterval.setSingleStep(5000)
		self.servoThreadInterval.setProperty("value", 1000000)
		self.servoThreadInterval.setObjectName(_fromUtf8("servoThreadInterval"))
		self.horizontalLayout_6.addWidget(self.servoThreadInterval)
		self.groupBox_3 = QtGui.QGroupBox(lh_gui)
		self.groupBox_3.setGeometry(QtCore.QRect(10, 150, 81, 51))
		self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
		self.layoutWidget2 = QtGui.QWidget(self.groupBox_3)
		self.layoutWidget2.setGeometry(QtCore.QRect(0, 20, 76, 23))
		self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
		self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget2)
		self.horizontalLayout_7.setMargin(0)
		self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
		self.logscaleY = QtGui.QRadioButton(self.layoutWidget2)
		self.logscaleY.setChecked(True)
		self.logscaleY.setObjectName(_fromUtf8("logscaleY"))
		self.buttonGroup = QtGui.QButtonGroup(lh_gui)
		self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
		self.buttonGroup.addButton(self.logscaleY)
		self.horizontalLayout_7.addWidget(self.logscaleY)
		self.logscaleX = QtGui.QRadioButton(self.layoutWidget2)
		self.logscaleX.setObjectName(_fromUtf8("logscaleX"))
		self.buttonGroup.addButton(self.logscaleX)
		self.horizontalLayout_7.addWidget(self.logscaleX)
		self.groupBox_4 = QtGui.QGroupBox(lh_gui)
		self.groupBox_4.setGeometry(QtCore.QRect(90, 150, 351, 51))
		self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
		self.showText = QtGui.QLineEdit(self.groupBox_4)
		self.showText.setGeometry(QtCore.QRect(0, 20, 341, 23))
		self.showText.setObjectName(_fromUtf8("showText"))
		self.showNotDisplayedBins = QtGui.QCheckBox(lh_gui)
		self.showNotDisplayedBins.setGeometry(QtCore.QRect(10, 210, 231, 21))
		self.showNotDisplayedBins.setObjectName(_fromUtf8("showNotDisplayedBins"))

		self.retranslateUi(lh_gui)
		QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), lh_gui.accept)
		QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), lh_gui.reject)
		QtCore.QMetaObject.connectSlotsByName(lh_gui)

	def retranslateUi(self, lh_gui):
		lh_gui.setWindowTitle(_translate("lh_gui", "Latency Histogram", None))
		self.run_lh.setText(_translate("lh_gui", "Run Latency Histogram", None))
		self.groupBox.setTitle(_translate("lh_gui", "Base Thread Options", None))
		self.showBase.setText(_translate("lh_gui", "Show Base Thread", None))
		self.label_2.setText(_translate("lh_gui", "Bin Size", None))
		self.label_3.setText(_translate("lh_gui", "Bins", None))
		self.label.setText(_translate("lh_gui", "Thread Interval", None))
		self.baseThreadInterval.setSuffix(_translate("lh_gui", "ns", None))
		self.groupBox_2.setTitle(_translate("lh_gui", "Servo Thread Options", None))
		self.label_4.setText(_translate("lh_gui", "Bin Size", None))
		self.label_5.setText(_translate("lh_gui", "Bins", None))
		self.label_6.setText(_translate("lh_gui", "Thread Interval", None))
		self.servoThreadInterval.setSuffix(_translate("lh_gui", "ns", None))
		self.groupBox_3.setTitle(_translate("lh_gui", "LogScale", None))
		self.logscaleY.setText(_translate("lh_gui", "Y", None))
		self.logscaleX.setText(_translate("lh_gui", "X", None))
		self.groupBox_4.setTitle(_translate("lh_gui", "Display Text", None))
		self.showNotDisplayedBins.setText(_translate("lh_gui", "Show Count of Bins not Displayed", None))

